bold-commerce/go-shopify

image.go
Without this the "Position" field was always set to 0, inserting the image at the beginning.  When omitted it is appended at the end.   You can set the Position explicitly to 1 to set it as the first image.  Same with other fields, they don't make sense to send on creation, or when updating.
Probably for most APIs there is little difference sending empty values.  The problem here is the "Position", which the empty value has a meaning to shopify (i.e. insert it at start).     For me, just flagging Position as omit if empty would be ok ... but the better is probably to set them all.
@andrewhoff regarding your [comment](https://github.com/getconversio/go-shopify/pull/116#issuecomment-419929844), I took a look at some of the test and wasn't sure what test would be appropriate here.  The …
=> Omit all fields in Image if empty.  Should only send when populated.

goshopify.go, goshopify_test.go
* Add func `(a *App) NewClient(string, string) *Client` that calls the global `NewClient(*App, string, string) *Client` function. This was done to make components that create on-demand clients easier to unit test as it lets us define an interface for the shopify app and create a mock.
=> Add NewClient method to App struct

shop.go
`primary_location_id` - is an undocumented shop property that is still pretty useful:
> "Primary_location_id" on the shop.json is a property that will always return the "location_id" of the 'Shipping Origin' which is a setting in the Shopify admin under shipping.  This is the address used to calculate the default shipping rates.
[Source](https://ecommerce.shopify.com/c/api-announcements/t/updated-deadline-aug-1st-deprecation-important-changes-to-productvariant-refund-and-fulfillment-apis-513771)
Shopify API libraries in other languages [use this property](https://github.com/MONEI/Shopify-api-node/blob/master/index.d.ts#L1802). And it is likely to be added to the doc soon \[[proof](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/api-documentation-issues-222215)\].
=> Add primary location ID to Shop struct

customer.go, customer_test.go
* Makes a breaking change to a method just recently added. Missing from the Shopify API documentation was the fact that this endpoint appears to take the same arguments as GET /admin/orders.json.
=> Add options to list customer orders

fixtures/inventory_item.json, fixtures/inventory_items.json, goshopify.go, inventory_item.go, inventory_item_test.go
* Add an inventory item service to the client that supports list, get, and update
Although the Get operation of the inventory API doesn't have any documented options, I added the options argument anyway so we can maintain backwards compatibility if any are ever added.
=> Add inventory item API

fulfillment.go
From [Shopify's REST API Doc on Fulfillments](https://help.shopify.com/en/api/reference/shipping-and-fulfillment/fulfillment): 
> `notify_customer`: Whether the customer should be notified. If set to true, then an email will be sent when the fulfillment is created or updated. For orders that were initially created using the API, the default value is false. For all other orders, the default value is true.Whether the customer should be notified. If set to true, then an email will be sent when the fulfillment is created or updated. For orders that were initially created using the API, the default value is false. For all other orders, **the default value is true**.
This PR removes `omitempty` from the JSON tag because it prevents `false` from being sent, and thus the default behavior from …
=> Remove omit_empty from json tag for Fulfillment.NotifyCustomer

goshopify.go, goshopify_test.go, oauth_test.go, product.go, product_test.go
See original pr https://github.com/bold-commerce/go-shopify/pull/73 from @brendankay. Most credits to him I just cleaned up some errors/header response but unfortunately botched my rebase and lost my commit on top of his. This also rebases on master so that it can be merged immediately(there were a couple conflicts).
Main differences:
- several errors and regex cleanup(move to global instead per function call)
- refactor header handling to just be return values since headers are never actually sent and passing around pointers to empty values in order to get a return value isn't the greatest. More importantly this moves the api changes to private methods which the current methods call so that we can keep the public api the same and not break anything. If you did want to commit to this api …
=> Add support for pagination via header refactored

.travis.yml, goshopify_test.go, usagecharge_test.go
Refactors the usagecharge test to not use DeepEqual any more as for some reason those tests stopped failing pre 1.13. Also added go 1.14 and updated the default build container to bionic.
=> refactor usagecharge test, added go 1.14 and bionic

order.go, order_test.go
It looks like the package did not had support for cursor based navigation for the orders, so I looked at the commits for the product navigation and created similar one for orders.
=> add cursor-based pagination for orders

go.mod
When using go modules you have to include the major version prefix in the module definition after v0 and v1.
https://github.com/golang/go/wiki/Modules#semantic-import-versioning
>If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg"). This includes the paths used in go get commands (e.g., go get github.com/my/mod/v2@v2.0.1. Note there is both a /v2 and a @v2.0.1 in that example. One way to think about it is that the module name now includes the /v2, so include /v2 whenever you are using the module name).
This will fix pkg.go.dev not showing the latest …
=> Update go.mod to include major version(fix modules, pkg.go.dev)

fixtures/shippinglines/requested_fulfillment_service_id_invalid.json, fixtures/shippinglines/requested_fulfillment_service_id_null.json, fixtures/shippinglines/requested_fulfillment_service_id_number.json, fixtures/shippinglines/valid.json, order.go, order_test.go
- Implemented custom unmarshaler to handle requested_fulfillment_service_id sometimes being returned as json numbers or json nulls instead of json strings.
=> Create custom unmarshaller for ShippingLines (#71)

order.go, order_test.go
As per Shopify API there are three actions on the `Order` resource that haven't been implemented in this package yet. This PR introduces these new actions as methods on the `OrderService`:
- Cancel order, with options for notes or refund amount
- Close order
- Re-open order
Ref: https://shopify.dev/docs/admin-api/rest/reference/orders/order?api[version]=2020-04#cancel-2020-04
=> Add Order actions: Cancel, Close and Open

.travis.yml, README.md
- dropped versions 1.7, 1.8, and 1.9 from build matrix
=> Drop support for Go versions 1.7, 1.8, 1.9

fixtures/product_listing.json, goshopify.go, product_listing.go, product_listing_test.go
I have added support for the Product Listing endpoint which I am using for developing a sales channel app. The endpoint is used to read, create and delete products that are shared with the sales channel app. 
Shopify documentation:
https://shopify.dev/docs/admin-api/rest/reference/sales-channels/productlisting
=> Add ProductListing support for Sales Channel Apps

goshopify.go, goshopify_test.go
I discovered this Shopify request:
```
GET: https://redacted.myshopify.com/admin/api/2020-10/products.json?collection_id=redacted&limit=250&page_info=redacted
```
Returns this response:
```
{"errors":{"collection_id":"collection_id cannot be passed when page_info is present. See https:\/\/help.shopify.com\/api\/guides\/paginated-rest-results for more information."}}
```
Which was not covered by the client lib.
=> Fix error unmarshaling when key value is string

fixtures/orderlineitems/valid.json, order.go, order_test.go
Adding discount_allocations in LineItem struct, regarding newest [Shopify api](https://shopify.dev/docs/admin-api/rest/reference/orders/order).
=> Add discount_allocations field to order's line_item

price_rule.go, price_rule_test.go
- prior to this change it was impossible to call the Shopify API
specifying these fields since the type was not exposed.
Closes #143 if merged.
=> Add PriceRule prerequisite field setters

customcollection_test.go, customer_test.go, fixtures/metafield.json, metafield.go, metafield_test.go, order_test.go, page_test.go, product_test.go, smartcollection_test.go, variant_test.go
- prior to this change it was impossible to call the Shopify API
with this field since it was newly added in 2021-07
=> Add Metafield Type field (#175)

draft_order.go, fixtures/orderlineitems/valid.json
This is to report an error in the JSON tag of the "AppliedDiscount" structure described in draft_order.go.
In the "Title" field of this structure, the JSON tag is written as "applied_discount", but it should be written as "title". 
See Shopify API documentation:
https://shopify.dev/docs/admin-api/rest/reference/orders/draftorder
=> Change JSON field names and JSON tag

draft_order.go
Before this commit, the JSON tag of the NoteAttributes field in the DraftOrder struct
was singular but should be plural.
See Shopify API documentation:
https://shopify.dev/docs/admin-api/rest/reference/orders/draftorder
=> Fix draft order note attributes JSON tag

draft_order.go
New field to allow setting `tax_exempt` on draft orders (see DraftOrder properties under https://shopify.dev/docs/admin-api/rest/reference/orders/draftorder).
From documentation:
> Whether taxes are exempt for the draft order. If set to false, then Shopify refers to the taxable field for each line_item. If a customer is applied to the draft order, then Shopify uses the customer's tax_exempt field instead.
Field is `*bool` to distinguish between setting value to false or leaving value unchanged for updates.
=> Support for tax_exempt in draft orders

webhook.go
Currently the Create method doesn't work at all, since we always send an empty "api_version" to Shopify. The api_version is read-only, and as such, Shopify doesn't allow you to pass it as an argument at all, therefore the request fails on validation.
=> fix: Omit empty API version for webhook

fixtures/inventory_item.json, inventory_item.go, inventory_item_test.go
This PR adds fields to handle Harmonized Tariff Schedule codes to the InventoryItem type.  These fields exist in [Shopify's API docs](https://shopify.dev/docs/api/admin-rest/2023-04/resources/inventoryitem#resource-object) and are used to handle international shipments.
=> Add HS (HTS) Code fields, as per fields supported by Shopify's API.

order.go
You can see the fields existing at least since 2022-07 version: https://shopify.dev/docs/api/admin-rest/2022-07/resources/order
=> fix: Add several missing fields to the Order model

customcollection_test.go, customer_test.go, draft_order_test.go, fixtures/metafield.json, metafield.go, metafield_test.go, order_test.go, page_test.go, product_test.go, smartcollection_test.go, variant_test.go
The `ValueType` field of a Metafield was deprecated some time long ago (2021?).  As of API version 2023-07 it is no longer supported.  The `Type` field should be used instead.  This removes the `ValueType` field from the `Metafield` type.
=> Remove ValueType field from Metafields since it was deprecated.

customcollection_test.go, customer_test.go, draft_order.go, draft_order_test.go, fixtures/metafield.json, metafield.go, metafield_test.go, order.go, order_test.go, page_test.go, product.go, product_test.go, smartcollection_test.go, variant.go, variant_test.go
Define types and constants for well-defined field values to aid in code editor type checking and auto-completion and in reducing back-and-forth between code and Shopify docs to check acceptable values.  Since Shopify limits the values certain fields can accept, this library should do so as well!
Shopify defines acceptable values for certain fields.  This defines those values, and an associated type, so that users are less likely to provide an unacceptable value.  Code editors may even provide a list of acceptable values for a field for auto-completion.  This is really just a code-writing improvement to prevent having to look up the acceptable values for a field in the Shopify API docs.
This should not break any existing code since the new types are all strings and string values, in …
=> Define consts for well known values.

goshopify.go, logger_test.go
- Remove duplicate response logging
- Output Shopify request id (very important for reporting issues) when debug log is enabled
=> Logging Improvements 

shop.go, shop_test.go
This adds an easy way to access the metafields on the shop resource.
In order to reuse the existing interfaces, the methods still accept a resource id, but we just ignore that value
```golang 
metafields, err := client.Shop.ListMetafields(0, nil)
```
=> Add Metafield accessor to Shop

carrier.go, goshopify.go, graphql.go, graphql_test.go, options.go
This is a re-introduction of an old PR by another person, trimmed down to just the GraphQL Client and a typo-fix
https://github.com/bold-commerce/go-shopify/pull/118
I'm not sure why the original one got closed, but I've succeessfully used it for making mutations with queries
```golang
req := `mutation webPixelCreate($webPixel: WebPixelInput!) {
webPixelCreate(webPixel: $webPixel) {
userErrors {
code
field
message
}
webPixel {
settings
id
}
}
}`
settings, err := json.Marshal(map[string]interface{}{
"accountID": fmt.Sprintf("%d", websiteID),
})
if err != nil {
return err
}
variables := map[string]interface{}{
"webPixel": map[string]interface{}{
"settings": string(settings),
},
}
var foo struct {
}
client.GraphQL.Query(req, &variables, &foo)
```
=> Add GraphQL endpoint

asset_test.go, carrier.go, customer_address.go, draft_order_test.go, goshopify.go, logger_test.go, order_test.go, product_listing.go
- Comment out unused code.
- Fix incorrect JSON struct tag (missing opening double-quote).
- Remove unneeded type inside slice of type ("redundant type from array, slice, or map composite literal" warning).
---
There are a lot of other warnings shown by `staticcheck` that were not fixed (`staticcheck` isn't in use for this repo).  Most of these warnings are for the checks listed below.  Fixing these is a rather big change, just due to volume of lines changed.   **Whether or not we want to implement `staticcheck` is the question.**
- ST1003 (using Api instead of API in struct field name).
- ST1021 (not starting the documentation of an exported type with it's name.
- ST1020 (not starting the documentation of an exported method or func with the method's name).
Changing field names per …
=> Fix some linting warnings (plus future use of staticcheck?)

order.go
The TotalPriceUSD struct field (on the Order type) no longer works.  It was deprecated in Oct. 2022.  See https://shopify.dev/docs/api/release-notes/2022-10#:~:text=resource%20is%20deprecated%3A-,total_price_usd,-Subscription%20billing%20cycles
Also, mark some other fields that are deprecated per the linked Shopify doc as well.  I have not tested to confirm if these fields still exist or not.  Marking these fields as deprecated should inform users when using a code editor that shows hints not to use this field, or to test it more thoroughly.
=> Remove long-term deprecated, and no longer functioning, total_price_usd field

fixtures/fulfillment_order.json, fulfillment_order.go
I've made the datetime fields (created_at, updated_at, fulfill_at, fulfill_by) consistent between the `FulfilmentOrder` and the `Order` structs. 
I've also replaced the `OnlyDate` struct with `*time.Time` in the `FulfilmentOrder` struct, as the actual REST response from Shopify contains a datetime, not just a date:
I've updated this in the fixtures to make the tests pass.
=> Fixed time parsing FulfilmentOrder

order.go
I've added a few missing fields from the API to the Order struct
=> Added total_price_set, total_shipping_price_set, total_tax_set to Order

product.go
Add the status query param to the product list options.
Ref: https://shopify.dev/docs/api/admin-rest/2023-07/resources/product#get-products?ids=632910392,921728736
Api version: 2023-07
**Note:** the type ProductStatus needs to be exported and if we want to expose this query parameter for the list orders endpoint the same needs to happen.
=> feat: add product status to list options

fulfillment.go
Added support for creating Fulfillments under this scenario - https://shopify.dev/docs/api/admin-rest/2023-01/resources/fulfillment#post-fulfillments
Issue was also mentioned here - https://github.com/bold-commerce/go-shopify/issues/219
=> Create a fulfillment for one or many fulfillment orders

fixtures/fulfillment_accept.json, fixtures/fulfillment_event.json, fixtures/fulfillment_events.json, fixtures/fulfillment_reject.json, fixtures/fulfillment_send.json, fulfillment_event.go, fulfillment_event_test.go, fulfillment_request.go, fulfillment_request_test.go, fulfillment_service.go, goshopify.go
adds fulfillment event resource and fulfillment request resource
comment if any edits
tested OK
=> adds `fulfillment_event` and `fulfillment_request`

fixtures/shippinglines/requested_fulfillment_service_id_null.json, fixtures/shippinglines/requested_fulfillment_service_id_number.json, fixtures/shippinglines/valid.json, order.go, order_test.go
this field described here https://shopify.dev/docs/api/admin-rest/2023-07/resources/draftorder
=> add handle field to shipping lines

goshopify.go, goshopify_test.go
Retries on 429 (rate limit) were not working for me (except for GET requests). I would get these errors (retries result in a 400 Bad Request every time):
```
[DEBUG] PUT: https://mydomain.myshopify.com/admin/api/2023-07/metafields/30029242335523.json
[DEBUG] SENT: {"metafield":{"created_at":"2023-08-30T19:55:54-06:00","description":"The SKU of the product.","id":30029242335523,"key":"sku","namespace":"ns","owner_id":8557574947107,"own er_resource":"product","updated_at":"2023-08-30T19:55:54-06:00","value":"8bp-101009","type":"single_line_text_field","admin_graphql_api_id":"gid://shopify/Metafield/30029242335523"}}
[DEBUG] Shopify X-Request-Id: 6676e531-ee1e-4efa-96b2-88682553f930
[DEBUG] RECV 429: 429 Too Many Requests
[DEBUG] RESP: {"errors":"Exceeded 2 calls per second for api client. …
```
=> Don't re-use empty body on retry

customer.go, customer_test.go, fixtures/customer.json
Sorry, but there was a bug in [the earlier PR](https://github.com/bold-commerce/go-shopify/pull/260), so I created a corrected PR!
=> Fixing Bug Marketing UpdatedAt in Customer is not pointer type

recurringapplicationcharge.go
add RecurringApplicationCharge missing field 'currency'
=> add RecurringApplicationCharge missing field 'currency'

api_permissions.go, api_permissions_test.go, goshopify.go
Add the ability to uninstall an app over the Shopify REST API by calling DELETE on the admin/api_permissions resource. Documentation for this functionality is found on Shopify API docs [here](https://shopify.dev/docs/apps/auth/installation/uninstall-app). Note that DELETE is the only method allowed on the api_permissions resource, hence it is the only method implemented.
I’ve added a test and tested manually to confirm this works, but please let me know if I’ve missed anything!
=> feat: add app uninstall functionality

product.go
close #253 
- add field `title`
=> fix: ProductListOptions are missing some fields (#253)

fixtures/shippinglines/requested_fulfillment_service_id_invalid.json, fixtures/shippinglines/requested_fulfillment_service_id_null.json, fixtures/shippinglines/requested_fulfillment_service_id_number.json, fixtures/shippinglines/valid.json, order.go, order_test.go
Update ShippingLines.Id to string from uint64
While querying the AbandonedCheckout endpoint the resulting response from shopify rest  api . the Id is not a number but a string. Thus throwing an error while unmarshaling the records.
=> Fix ShippingLines.Id type

customer.go, customer_test.go, order.go, order_risk.go, order_risk_test.go, order_test.go, payments_transactions.go, payments_transactions_test.go, payouts.go, payouts_test.go, product.go, product_listing.go, product_listing_test.go, product_test.go
This relates to https://github.com/bold-commerce/go-shopify/issues/230 
It looks like the `List` method only returns the first page for all of the resources that we have a `ListWithPagination`.
I wasn't super comfortable breaking backwards compatibility, so with this PR I'm adding a `ListAll` method that utilizes `ListWithPagination` to pull all of the items
=> Add ListAll methods to resources with ListWithPagination methods

assigned_fulfillment_order.go
VariantId is missing in the official documentation but it's being transmitted and it's important for mapping the products of the orders
=> add VariantId to AssignedFulfillmentOrder

fixtures/image.json, fixtures/images.json, image.go, image_test.go
The tag is already supported by Shopify as evident in https://shopify.dev/docs/api/admin-rest/2024-01/resources/product-image
=> Add alt member variable to Image tag. 

fixtures/shippinglines/requested_fulfillment_service_id_invalid.json, fixtures/shippinglines/requested_fulfillment_service_id_null.json, fixtures/shippinglines/requested_fulfillment_service_id_number.json, fixtures/shippinglines/valid.json, order.go, order_test.go
The shipping_lines return their ID as an uint64, not a string. I've updated this in the fixtures as well.
=> Changed order.shipping_lines.id to uint64

order.go, variant.go
Added missing fields from RefundLineItem.
Additionally updated presentmentPrices to re-use the same object (no sense in defining the same type multiple places with different names)
=> Added subtotal and total tax sets to RefundLineItem

order.go, order_test.go
Removes deprecated delivery_category field on order shipping lines.
https://shopify.dev/changelog/removal-of-the-delivery_category-field-on-order-shipping-lines
=> Removes delivery_category field

goshopify_test.go, usagecharge.go, usagecharge_test.go
https://shopify.dev/changelog/removal-of-usagecharge-billing_on-field-on-admin-rest-api
> As of Admin REST API version 2023-10, the following UsageCharge fields have been deprecated: billing_on.
> Learn more about the UsageCharge object on [Shopify.dev](https://shopify.dev/docs/api/admin-rest/2022-10/resources/usagecharge).
=> deprecate Usagecharge->BillingOn

order.go
Added current_quantity to LineItem. 
This addition is documented in the following release notes
https://shopify.dev/docs/api/release-notes/2024-01#rest-admin-api-changes
=> added current_quantity to LineItem

customer.go, customer_test.go, order.go, usagecharge.go
* Added Currency and UpdatedAt properties in UsageCharge
* Removed Deprecated fields `accepts_marketing` and `accepts_marketing_updated_at` from customer object
* Exporting OrderFinancialStatus and OrderFulfillmentStatus from Order
=> Code update for `2024-01`

draft_order.go, order.go, order_risk.go, variant.go
=> fix: Export some enums values #303

page.go, page_test.go, util.go
This PR adds `Published` field to Page to make it possible to pass `published` parameter for create/update.
Also not to let user confuse, the field will be consistent with `published_at` when it's read.
```shell
curl -d '{"page":{"title":"Warranty information","body_html":"<h2>Warranty</h2>\n<p>Returns accepted if we receive items <strong>30 days after purchase</strong>.</p>","published":false}}' \
-X POST "https://your-development-store.myshopify.com/admin/api/2024-07/pages.json" \
-H "X-Shopify-Access-Token: {access_token}" \
-H "Content-Type: application/json"
```
https://shopify.dev/docs/api/admin-rest/2024-07/resources/page#post-pages-examples
=> Add published param to Page

location.go
This PR adds `MetafieldService` implementation for `LocationService`, similarly to how it has been handled in other Shopify resources.
=> feat: add MetafieldService to LocationService

order.go
Some price sets were missing in the Order and TaxLine types which meant it wasn't possible to access the presentational amount. 
**Note** it seems TotalDiscountSet was added but it was wrongly mapped to the JSON. It should be `total_discounts_set` not `total_discount_set`. I've left it in to avoid a breaking change (although it wont be working correctly if people are using it). Happy to remove it if that's best
=> add missing price sets in order

fixtures/inventory_item.json, inventory_item.go, inventory_item_test.go
Fix: update country_harmonized_system_codes type in InventoryItem
The country_harmonized_system_codes field was previously defined as []string, but according to Shopify’s API documentation, it should be an array of objects. This PR introduces the CountryHarmonizedSystemCode struct and updates the InventoryItem type to use []CountryHarmonizedSystemCode, ensuring the JSON format matches the expected schema.
[Link to the issue](https://github.com/bold-commerce/go-shopify/issues/318)
=> Update country_harmonized_system_codes type in InventoryItem

order.go
Add the PaymentId and Receipt fields to the Transaction under the Order.
=> Add the PaymentId and Receipt fields to the Transaction under the Order.

order.go
This PR adds the `total_outstanding` to the order struct.
https://shopify.dev/docs/api/admin-rest/2025-07/resources/order#resource-object
=> Add TotalOutstanding field to Order struct
