- fixtures/variant.json
- variant.go
- variant_test.go
Added InventoryItemId to the Variant struct so we can get the inventory_item_id from shopify
> Update Variant Struct

- fixtures/storefront_access_token.json
- fixtures/storefront_access_tokens.json
- goshopify.go
- storefrontaccesstoken.go
- storefrontaccesstoken_test.go
Add StorefrontAccessToken support
API docs: https://help.shopify.com/api/reference/access/storefrontaccesstoken
> Add storefront access token service

- customer.go
- customer_test.go
* Add ListOrders method to the customer service to hit the /admin/customers/{id}/orders.json endpoint
> Add list customer orders endpoint

- .gitignore
- oauth.go
- oauth_test.go
- product_test.go
- variant.go
- variant_test.go
- This Closes #1
- Gofmt project again, whoops!
- Adding a more verbose verify webhook method that outputs an error for
each different thing that might go wrong with a webhook request. With
tests.
> Adding debug webhook verify method

- theme.go
> Fix tag of theme resource

- customer_address.go
- was causing unexpected behaviour with partial updates
> Added omitempty tag for CustomerAddress properties

- order.go
add two new properties: Subtotal and TotalTax
> add properties to RefundLineItem

- customer.go
- customer_test.go
- fixtures/customer_tags.json
Expose endpoint to get all unique tags across all customers
> add endpoint to get all tags across customers

- order.go
- order_test.go
It allows to update notes, customer, address and so on
> Add order update endpoint

- draft_order.go
- order.go
LineItem should have AppliedDiscount property. 
https://help.shopify.com/en/api/reference/orders/draftorder#create
> Add AppliedDiscount to LineItem

- fixtures/variant_with_metafields.json
- variant.go
- variant_test.go
Add metafields to the shopify variants
> Add metafields to the shopify variant struct

- fixtures/shop.json
- shop.go
- shop_test.go
- updates fixture, model and tests
> Adding pre_launch_enabled to shop model

- goshopify.go
- goshopify_test.go
- implement methods to fields access
> Adding methods response error struct

- goshopify.go
- goshopify_test.go
This PR makes available the rate limit information as returned by Shopify in the headers of the response to an API request. [Relevant Shopify API docs are here](https://help.shopify.com/en/api/reference/rest-admin-api-rate-limits#rate-limits-header).
I'm not sure if putting the results into a struct in the client is the best way to do this, let me know if you have suggestions for how to handle this better.
> add ratelimit info

- page.go
> fix: prevent sending unexpected page's field

- .travis.yml
- Dockerfile
- Makefile
- README.md
- docker-compose.yml
- make.bat
* NewClient options documented, WithVersion and WithRetry
* Added Makefile and make.bat for easier testing (instead of copy/paste from README.md)
* Renamed docker-compose app from dev to test
* Named the test image `go-shopify:latest`
* Upgraded testing container to 1.14.1-alpine + go mod
* Docuemented new Makefile
* Updated Manual testing docs for alpine container (bash => sh)
> Docs and Testing Procedure Cleanup

- go.mod
- goshopify.go
Added existing FulfillmentService to the go-shopify client.
> FulfillmentService was missing from the client

- collection.go
- collection_test.go
- goshopify.go
Added support for the Shopify Collection endpoint. 
See: [https://shopify.dev/docs/admin-api/rest/reference/products/collection](https://shopify.dev/docs/admin-api/rest/reference/products/collection)
> Add Collection endpoint

- options.go
- options_test.go
- add WithHTTPClient as an option
> Add option to support custom http client

- collection_test.go
- fixtures/metafield.json
- metafield.go
- metafield_test.go
- product_listing_test.go
I assume c87c24c is not wanted.
> Add AdminGraphqlAPIID to Metafield

- access_scopes.go
- access_scopes_test.go
- fixtures/access_scopes.json
- goshopify.go
- supporting the oauth/access_scopes.json endpoint to check allowed scopes for a given token
> Add access scopes endpoint

- product.go
```
(add): product status field, for being able to set status of products:
- draft
- active
- archived
```
https://shopify.dev/api/admin-rest/2021-10/resources/product
> (add): product status field

- draft_order.go
- order.go
- order_test.go
DiscountPrice, PriceSet and DiscountedPriceSet are added to ShippingLines
Test .json file for shipping lines already has those fields, they were missing in the code so i just added them in the struct and in the test.
> Add discounted price to shipping lines

- blog.go
> Blog struct add a new field

- price_rule.go
Where validation occurs in the price-rule setters, error messaging has been improved.
> Improves logging around price-rule setters

- oauth.go
- oauth_test.go
https://shopify.dev/tutorials/display-data-on-an-online-store-with-an-application-proxy-app-extension
> Introduce VerifySignature to check the signature that is passed when handling app proxy

- carrier.go
- carrier_test.go
- fixtures/carrier_service.json
- fixtures/carrier_services.json
- goshopify.go
Support the carrier services API https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/carrierservice
> Support carrier services API

- fixtures/payout.json
- fixtures/payouts.json
- fixtures/payouts_filtered.json
- goshopify.go
- payouts.go
- payouts_test.go
- util.go
- util_test.go
Let me know if I've missed something and I'll gladly add it.
I have done some manual testing and everything works as expected.
The only open question is how to handle the date. 
We either 
1. keep it like this as a custom format, and let consumers convert to a time.Time format if they need it.
2. set it as a string, and do some manual conversion after the data is fetched
I honestly would prefer the 1st option as it is more elegant and it doesn't require looping through the data again, but I am happy to hear your opinions as well.
> Add support for the payouts model

- order.go
- order_test.go
> add-order-delete

- abandoned_checkout.go
- abandoned_checkout_test.go
- goshopify.go
> Add abandoned checkout

- fixtures/gift_card/get.json
- fixtures/gift_card/list.json
- gift_card.go
- gift_card_test.go
- go.mod
- goshopify.go
> Add gift-card and the tests

- assigned_fulfillment_order.go
- assigned_fulfillment_order_test.go
- fulfillment_order.go
- goshopify.go
adds `assigned_fulfillment_order.json` resource
comment if any edits
> adds `assigned_fulfillment_order`

- order.go
this field described here https://shopify.dev/docs/api/admin-rest/2023-10/resources/refund#resource-object
> add order adjustments in refund

- order.go
> add `presentment_currency` & `inventory_behaviour` to Order

- metafield.go
> feat: Expose the MetafieldType type

- product.go
Third times the charm. Sorry for the notifications 👎
> fix spelling

- go.mod
> bump go.mod to v4

- README.md
GetAccessToken requires a context along with shopname and code
> Updates example for GetAccessToken context

- order.go
Add refund_shipping_lines as they are missing in the API. https://shopify.dev/docs/api/admin-rest/2025-04/resources/refund
> Refund shipping lines
